site_name: The MERC project
site_url: https://mercorg.github.io/merc-website/
theme:
  name: material
  palette:
    - scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  language: en
  features:
    # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.instant

plugins:
  - privacy # Plugin that downloads all external resources and serves them locally to enhance privacy.
  - search

repo_name: MERCorg/merc
repo_url: https://github.com/MERCorg/merc/

# Definition for the left-hand navigation menu
nav:
  - Home: index.md
  - Development:
    - developer/testing.md
    - developer/term_trait.md
  - Maintainers:
    - maintainers/general.md
    - maintainers/publishing.md
  - Links:
    - 'Issue Tracker': https://github.com/MERCorg/merc/issues
    - 'Documentation': https://mercorg.github.io/merc/
    - 'Coverage': https://mercorg.github.io/merc/coverage/

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Enable markdown extensions
markdown_extensions:
  - admonition # The admonition extension allows you to create callout boxes.
  - pymdownx.highlight: # Use Pygments for syntax highlighting at build time
      use_pygments: true    
  - pymdownx.superfences